planning_plugins:
  - ompl_interface/OMPLPlanner
planning_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/FixStartStateBounds
  - default_planning_request_adapters/FixStartStateCollision
  - default_planning_request_adapters/FixWorkspaceBounds
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/FixStartStateBounds
  - default_planning_request_adapters/FixStartStateCollision
  - default_planning_request_adapters/FixWorkspaceBounds
manipulator:
  planner_configs:
    - RRTConnect
  projection_evaluator: joints(joint_1,joint_2)
  longest_valid_segment_fraction: 0.005
